### ISSUE TITLE
PyPy does not define 'HOST_GNU_TYPE'

### ISSUE THREAD

**Issue by mattip** [benfogle/crossenv#102]
I am seeing reports that cross compilation recently broke for conda recipes that build for pypy + aarch64. For instance conda-forge/pypy3.6-feedstock#90, [matplotlib-feedstock](https://github.com/conda-forge/matplotlib-feedstock/pull/333#issuecomment-1274298870), [gz-math-feedstock](https://github.com/conda-forge/gz-math-feedstock/pull/4#issuecomment-1273836303).

It seems PyPy should provide `HOST_GNU_TYPE` but does not, and that only recently came to light. Are there other values missing as well? From the code line that uses this, would it be sufficient to quickly patch `HOST_GNU_TYPE` on the host conda-forge PyPY (i.e. only `linux-x86_64`) and later fix this more systematically, or is that going to cause problems elsewhere: https://github.com/benfogle/crossenv/blob/5c3b53aa2989fc442194e144fac90464dd4b3086/crossenv/__init__.py#L323

Is there a "commonly known values" for HOST_GNU_TYPE? It seems to be a command line option to the CPython build, and not something taken from `uname`.

**Comment by mattip** [comment]
Strangely, that failure does not appear for pypy + ppc64le. But maybe not worth going down that rabbit hole, I should just provide a value across the board.

**Comment by mattip** [comment]
Is that value used elsewhere in the code base?

**Comment by mattip** [comment]
There was a typo in the conda feedstock. See conda-forge/pypy3.6-feedstock#91. I will leave this open for discoverability, but it seems PyPy has a work-around for this.

**Comment by isuruf** [comment]
Since PyPy does set HOST_GNU_TYPE, this can be closed?

**Comment by mattip** [comment]
yes, closing.
