### ISSUE TITLE
Fortran cross compiler

### ISSUE THREAD

**Issue by bessman** [benfogle/crossenv#12]
Some Python modules (notably Scipy and accelerated Numpy) require a Fortran compiler in addition to a C compiler. Inside crossenv the C compiler is set to whatever was used to compile host-python, but the Fortran compiler is still the system Fortran compiler, e.g. /usr/bin/gfortran rather than /usr/bin/arm-linux-armhf-gfortran. This means that the build will fail or produce an unusable module.

**Comment by benfogle** [comment]
Like I mentioned in my comment for #11, numpy does things a little differently from everyone else. They build using a [*heavily* extended distutils ](https://github.com/numpy/numpy/tree/master/numpy/distutils) that they developed themselves, including their own Fortran compiler detection. I'm not sure that cross compiling prefixes are even a part of it.

If I'm reading [the source](https://github.com/numpy/numpy/blob/master/numpy/distutils/fcompiler/__init__.py#L112) correctly, then it looks like it might respect the F90 and F77 environment variables.

Even with crossenv, I'm afraid sometimes cross-compiling is an adventure.

**Comment by bessman** [comment]
F90 and F77 did the trick, thanks!
