### ISSUE TITLE
Allow setting host_sysconfigdata_file using command line.

### ISSUE THREAD

**Issue by isuruf** [benfogle/crossenv#31]
For some python installations there are multiple `_sysconfigdata*` files. (For eg: python packaged in conda)
In those cases, `crossenv` gives an error as it can't decide which file to use.

It'd be great to have a way to give a  `_sysconfigdata*` file on the command line.

**Comment by benfogle** [comment]
Just to clarify: from #29, are you trying to build macOS Anaconda modules from a Linux build machine?

**Comment by isuruf** [comment]
Yes
