### ISSUE TITLE
Document PYTHON_CROSSENV variable

### ISSUE THREAD

**Issue by virtuald** [benfogle/crossenv#33]
My setup.py conditionally runs an executable -- when cross compiling, it turns it off. I was looking for `_PYTHON_HOST_PLATFORM`, but crossenv deletes that?

Now I'm checking for PYTHON_CROSSENV... but I'd be happier if it were a documented way to detect crossenv.

**Comment by benfogle** [comment]
Crossenv also sets `sys.cross_compiling`, which can be used like `if getattr(sys, 'cross_compiling', False): ...`

Either one of those should work for you, but you're absolutely right: both of those should be documented.

**Comment by benfogle** [comment]
Closed by #59
