### ISSUE TITLE
Can't create venv

### ISSUE THREAD

**Issue by thomascatlee** [benfogle/crossenv#6]
**python -m crossenv /home/lx/platform3798C/pub/hi3798cv200/rootbox/usr/bin/python3.5 hisi_python --system-site-packages**
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 30, in <module>
    from pip._vendor.retrying import retry
ImportError: No module named 'pip._vendor.retrying'
ERROR: Command '['/home/lx/hisi_python/cross/bin/python', '-m', 'pip', '--disable-pip-version-check', 'install', '--ignore-installed', '--prefix=/home/lx/hisi_python/cross', 'pip==8.1.1', 'setuptools==20.7.0']' returned non-zero exit status 1
```

the cross/bin/python is a py file, that convert PATH between BUILD and HOST, I tested with test.py
```
import sys
print(sys.path)
```
it works. But when I use crosspython as a Interpreter and just import pip, the ImportError message was the same. And ```crosspython -m python``` error in the same way.

**Comment by benfogle** [comment]
I have a lightly tested fix in the master branch. The issue stems from patches made to the system installed version of Python that aren't present in stock Python. For this reason, and to make sure that build-python and host-python are really the same, I still recommend that you build Python from source and use that rather than the system installed version.
