### ISSUE TITLE
Shebang in 1.1.0 changed; activating venv fails

### ISSUE THREAD

**Issue by tgeulig** [benfogle/crossenv#63]
I tried upgrading to 1.1.0, but activating venv fails now:
```
/bin/sh: /home/geulig/linux.git/user/python_modules/venv/cross/bin/pip3: /home/geulig/linux.git/user/python/build/bin/python: bad interpreter: No such file or directory
make[2]: *** [Makefile:40: all] Error 1
```
The shebang of venv/cross/bin/pip3 is
`#!/home/geulig/linux.git/user/python/build/bin/python`
and yes, this file does not exist.

Version 1.0 still works. Here the shebang is
`#!/home/geulig/linux.git/user/python_modules/venv/cross/bin/python`

Setup is done like this:
```
PYTHONHOME="/opt/python-3.6.13" \
PYTHONPATH="/opt/python-3.6.13/lib/python3.6/site-packages:/opt/python-3.6.13/lib64/python3.6/lib-dynload" \
        /opt/python-3.6.13/bin/python3 -m crossenv /home/geulig/linux.git/user/python/build/python venv
. venv/bin/activate
```

Maybe this has something to do with the changes for #44/#46?

**Comment by benfogle** [comment]
I don't think it's #44/#46 because when the shebang line is changed, it get's changed to `#!/bin/sh`.

Is `/home/geulig/linux.git/user/python/build/python` a build directory? If so, does the same issue occur if you install it somewhere and run crossenv with the installed version?

**Comment by benfogle** [comment]
I can reproduce this when `host-python` is in a build directory. I am investigating the cause.

**Comment by tgeulig** [comment]
Yes, /home/geulig/linux.git/user/python/build/python is host-python.

I've tried your patch. Looks good again
