### ISSUE TITLE
_get_sysconfig_name() replacement may fail if called with arguments.

### ISSUE THREAD

**Issue by erykoff** [benfogle/crossenv#84]
We had some trouble cross-compiling with python3.8 here: https://github.com/conda-forge/eups-feedstock/pull/25 and it appears that the problem is that sometimes `_get_sysconfig_name()` may be called with arguments (specifically the system allows the `check_exists` argument.  (I don't know if the problem is with python3.8 specifically, or if this is just a coincidence).

A fix proposed here https://github.com/conda-forge/crossenv-feedstock/blob/e53608da2d70a5b72a9f1f5750331be5c017b9b8/recipe/0002-Fix-py38-support.patch is to add a dummy `*args` so that crossenv returns the correct value and simply swallows any arguments.

**Comment by isuruf** [comment]
@erykoff, this is a patch in conda in 3.8 that we removed for 3.9+ and is not an issue with `crossenv`.
