### ISSUE TITLE
Are there any plans to make this work with BSD?

### ISSUE THREAD

**Issue by iamthenoname** [benfogle/crossenv#93]

**Comment by benfogle** [comment]
Crossenv only supports Linux -> Linux cross compiling. BSD -> BSD might be possible, and might not even be to difficult. Linux -> BSD, etc., is probably something that can never be fully supported, as outlined [here](https://github.com/benfogle/crossenv/issues/28#issuecomment-678854468).

**Comment by iamthenoname** [comment]
That's unfortunate, thank you for the reply tho
